import type { DataRepo } from '../git/sync.js';

function lines(input: string[]): string {
  return `${input.join('\n')}\n`;
}

const SITE_TEMPLATE_FILES: Record<string, string> = {
  'site/package.json': lines([
    '{',
    '  "name": "nautilus-site",',
    '  "private": true,',
    '  "type": "module",',
    '  "scripts": {',
    '    "dev": "astro dev",',
    '    "build": "astro build",',
    '    "preview": "astro preview"',
    '  },',
    '  "dependencies": {',
    '    "astro": "^5.2.0",',
    '    "marked": "^15.0.6",',
    '    "yaml": "^2.7.1"',
    '  }',
    '}',
  ]),
  'site/astro.config.mjs': lines([
    "import { defineConfig } from 'astro/config';",
    '',
    'export default defineConfig({',
    '  output: "static",',
    '});',
  ]),
  'site/tsconfig.json': lines([
    '{',
    '  "extends": "astro/tsconfigs/strict"',
    '}',
  ]),
  'site/src/env.d.ts': lines(['/// <reference types="astro/client" />']),
  'site/src/layouts/ResearchLayout.astro': lines([
    '---',
    'interface Props {',
    '  title: string;',
    '  description?: string;',
    '}',
    '',
    'const { title, description } = Astro.props as Props;',
    '---',
    '<!doctype html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="utf-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '    <title>{title}</title>',
    '    {description && <meta name="description" content={description} />}',
    '    <style>',
    '      :root {',
    '        --bg: #f6f5f0;',
    '        --surface: #ffffff;',
    '        --ink: #1e2a28;',
    '        --muted: #5d6d68;',
    '        --accent: #0f766e;',
    '        --line: #d6ddd9;',
    '      }',
    '',
    '      * {',
    '        box-sizing: border-box;',
    '      }',
    '',
    '      body {',
    '        margin: 0;',
    '        font-family: "IBM Plex Sans", "Avenir Next", "Segoe UI", sans-serif;',
    '        color: var(--ink);',
    '        background:',
    '          radial-gradient(circle at top right, #d7ebe4, transparent 36%),',
    '          radial-gradient(circle at bottom left, #f0e5c8, transparent 44%),',
    '          var(--bg);',
    '        line-height: 1.6;',
    '      }',
    '',
    '      main {',
    '        max-width: 860px;',
    '        margin: 0 auto;',
    '        min-height: 100vh;',
    '        padding: 2rem 1rem 3rem;',
    '      }',
    '',
    '      .card {',
    '        background: var(--surface);',
    '        border: 1px solid var(--line);',
    '        border-radius: 12px;',
    '        padding: 1.1rem;',
    '      }',
    '',
    '      h1,',
    '      h2,',
    '      h3 {',
    '        line-height: 1.25;',
    '      }',
    '',
    '      a {',
    '        color: var(--accent);',
    '      }',
    '',
    '      .meta {',
    '        color: var(--muted);',
    '      }',
    '',
    '      .prose {',
    '        font-size: 1.03rem;',
    '      }',
    '',
    '      .prose table {',
    '        border-collapse: collapse;',
    '        width: 100%;',
    '      }',
    '',
    '      .prose th,',
    '      .prose td {',
    '        border: 1px solid var(--line);',
    '        padding: 0.4rem 0.55rem;',
    '        text-align: left;',
    '      }',
    '',
    '      @media (max-width: 640px) {',
    '        main {',
    '          padding-top: 1.2rem;',
    '        }',
    '      }',
    '    </style>',
    '  </head>',
    '  <body>',
    '    <main>',
    '      <slot />',
    '    </main>',
    '  </body>',
    '</html>',
  ]),
  'site/src/components/LastUpdated.astro': lines([
    '---',
    'const { value } = Astro.props as { value?: string | null };',
    "const formatted = value ? new Date(value).toLocaleString('en-US', {",
    "  dateStyle: 'medium',",
    "  timeStyle: 'short',",
    "  timeZone: 'UTC',",
    '}) : null;',
    '---',
    '{formatted && <p class="meta">Last researched: {formatted} UTC</p>}',
  ]),
  'site/src/components/SourceList.astro': lines([
    '---',
    'interface SourceRef {',
    '  url: string;',
    '  title: string;',
    '}',
    '',
    'const { sources } = Astro.props as { sources: SourceRef[] };',
    '---',
    '{sources.length > 0 && (',
    '  <section class="card" style="margin-top: 1.1rem;">',
    '    <h3>Sources</h3>',
    '    <ul>',
    '      {sources.map((source) => (',
    '        <li><a href={source.url}>{source.title}</a></li>',
    '      ))}',
    '    </ul>',
    '  </section>',
    ')}',
  ]),
  'site/src/components/TableOfContents.astro': lines([
    '---',
    'interface TaskSummary {',
    '  id: string;',
    '  title: string;',
    "  status: 'queued' | 'in_progress' | 'completed' | 'failed' | 'unknown';",
    '  route: string | null;',
    '}',
    '',
    'interface SectionSummary {',
    '  slug: string;',
    '  title: string;',
    '  description: string;',
    '  stats: {',
    '    total: number;',
    '    completed: number;',
    '    queued: number;',
    '    inProgress: number;',
    '    failed: number;',
    '  };',
    '  tasks: TaskSummary[];',
    '}',
    '',
    'const { sections = [] } = Astro.props as { sections: SectionSummary[] };',
    '',
    "function formatStatus(status: TaskSummary['status']): string {",
    '  if (status === "in_progress") return "in progress";',
    '  return status;',
    '}',
    '---',
    '{sections.map((section) => (',
    '  <section class="card" style="margin-top: 1rem;">',
    '    <h2>{section.title}</h2>',
    '    <p class="meta">{section.description}</p>',
    '    <p class="meta">',
    '      {section.stats.completed}/{section.stats.total} complete',
    '      {section.stats.inProgress > 0 && `, ${section.stats.inProgress} in progress`}',
    '      {section.stats.failed > 0 && `, ${section.stats.failed} failed`}',
    '    </p>',
    '    <ul>',
    '      {section.tasks.map((task) => (',
    '        <li>',
    '          {task.route ? <a href={`/${task.route}`}>{task.title}</a> : task.title} ',
    '          <span class="meta">({formatStatus(task.status)})</span>',
    '        </li>',
    '      ))}',
    '    </ul>',
    '  </section>',
    '))}',
  ]),
  'site/src/pages/index.astro': lines([
    '---',
    "import TableOfContents from '../components/TableOfContents.astro';",
    "import ResearchLayout from '../layouts/ResearchLayout.astro';",
    "import toc from '../generated/toc.json';",
    '',
    "const generatedAt = toc.generatedAt ? new Date(toc.generatedAt).toLocaleString('en-US', {",
    "  dateStyle: 'medium',",
    "  timeStyle: 'short',",
    "  timeZone: 'UTC',",
    '}) : null;',
    '',
    "const title = toc.project.title || 'Nautilus Research';",
    '---',
    '<ResearchLayout title={title} description={toc.project.scope}>',
    '  <h1>{title}</h1>',
    '  {toc.project.scope && <p>{toc.project.scope}</p>}',
    '  {generatedAt && <p class="meta">Heartbeat snapshot: {generatedAt} UTC</p>}',
    '  <TableOfContents sections={toc.sections} />',
    '</ResearchLayout>',
  ]),
  'site/src/pages/[...slug].astro': lines([
    '---',
    "import { readFile } from 'node:fs/promises';",
    "import { resolve } from 'node:path';",
    "import { marked } from 'marked';",
    "import { parse as parseYaml } from 'yaml';",
    "import LastUpdated from '../components/LastUpdated.astro';",
    "import SourceList from '../components/SourceList.astro';",
    "import ResearchLayout from '../layouts/ResearchLayout.astro';",
    "import pages from '../generated/pages.json';",
    '',
    'interface SitePage {',
    '  taskId: string;',
    '  title: string;',
    '  category: string;',
    '  outputPath: string;',
    '  route: string;',
    '}',
    '',
    'interface SourceRef {',
    '  url: string;',
    '  title: string;',
    '}',
    '',
    'interface FrontmatterData {',
    '  title?: string;',
    '  category?: string;',
    '  researchedAt?: string;',
    '  sources?: SourceRef[];',
    '}',
    '',
    'function parseFrontmatter(input: string): { data: FrontmatterData; body: string } {',
    '  if (!input.startsWith("---\\n")) {',
    '    return { data: {}, body: input.trim() };',
    '  }',
    '',
    '  const endIndex = input.indexOf("\\n---\\n", 4);',
    '  if (endIndex < 0) {',
    '    return { data: {}, body: input.trim() };',
    '  }',
    '',
    '  const yamlText = input.slice(4, endIndex);',
    '  const parsed = parseYaml(yamlText);',
    '  const data = (parsed && typeof parsed === "object") ? (parsed as FrontmatterData) : {};',
    '  return { data, body: input.slice(endIndex + 5).trim() };',
    '}',
    '',
    'function normalizeSources(value: unknown): SourceRef[] {',
    '  if (!Array.isArray(value)) return [];',
    '',
    '  const sources: SourceRef[] = [];',
    '  for (const source of value) {',
    '    if (!source || typeof source !== "object") continue;',
    '    const maybeUrl = (source as { url?: unknown }).url;',
    '    const maybeTitle = (source as { title?: unknown }).title;',
    '    if (typeof maybeUrl !== "string" || typeof maybeTitle !== "string") continue;',
    '    if (!maybeUrl.trim() || !maybeTitle.trim()) continue;',
    '    sources.push({ url: maybeUrl.trim(), title: maybeTitle.trim() });',
    '  }',
    '',
    '  return sources;',
    '}',
    '',
    'export function getStaticPaths() {',
    '  return pages.map((page) => ({',
    '    params: { slug: page.route },',
    '    props: { page },',
    '  }));',
    '}',
    '',
    'const { page } = Astro.props as { page: SitePage };',
    'if (!page.outputPath.startsWith("content/")) {',
    '  throw new Error(`Invalid output path for page ${page.route}: ${page.outputPath}`);',
    '}',
    '',
    'const markdownPath = resolve(process.cwd(), "..", page.outputPath);',
    'const rawMarkdown = await readFile(markdownPath, "utf-8");',
    'const parsed = parseFrontmatter(rawMarkdown);',
    'const sources = normalizeSources(parsed.data.sources);',
    'const title = parsed.data.title || page.title;',
    'const category = parsed.data.category || page.category;',
    'const researchedAt = parsed.data.researchedAt || null;',
    'const bodyHtml = await marked.parse(parsed.body);',
    '---',
    '<ResearchLayout title={title} description={category}>',
    '  <p><a href="/">Back to index</a></p>',
    '  <h1>{title}</h1>',
    '  <p class="meta">Category: {category}</p>',
    '  <LastUpdated value={researchedAt} />',
    '  <article class="card prose" style="margin-top: 1rem;" set:html={bodyHtml} />',
    '  <SourceList sources={sources} />',
    '</ResearchLayout>',
  ]),
  'site/src/generated/toc.json': lines([
    '{',
    '  "generatedAt": null,',
    '  "project": {',
    '    "title": "",',
    '    "scope": "",',
    '    "status": "scoping",',
    '    "updatedAt": null,',
    '    "siteUrl": ""',
    '  },',
    '  "sections": []',
    '}',
  ]),
  'site/src/generated/pages.json': lines(['[]']),
};

export async function scaffoldAstroSite(repo: DataRepo): Promise<void> {
  for (const [filePath, fileContent] of Object.entries(SITE_TEMPLATE_FILES)) {
    await repo.writeFile(filePath, fileContent);
  }
}
